const ARGENTINA_TIME_ZONE = 'America/Argentina/Buenos_Aires';

const argentinaFormatter = new Intl.DateTimeFormat('en-CA', {
  timeZone: ARGENTINA_TIME_ZONE,
  year: 'numeric',
  month: '2-digit',
  day: '2-digit',
  hour: '2-digit',
  minute: '2-digit',
  second: '2-digit',
  hourCycle: 'h23',
});

/**
 * Returns current Argentina time parts [year, month, day, hour, minute]
 */
export function getArgentinaDateTimeParts(): { year: number; month: number; day: number; hour: number; minute: number } {
  const parts = argentinaFormatter.formatToParts(new Date());
  const map: Record<string, string> = {};
  for (const part of parts) {
    if (part.type !== 'literal') {
      map[part.type] = part.value;
    }
  }

  const year = Number(map.year);
  const month = Number(map.month);
  const day = Number(map.day);
  const hour = Number(map.hour);
  const minute = Number(map.minute);

  if (!Number.isInteger(year) || !Number.isInteger(month) || !Number.isInteger(day) || !Number.isInteger(hour) || !Number.isInteger(minute)) {
    throw new Error('Invalid Argentina time parts from Intl.DateTimeFormat');
  }

  return { year, month, day, hour, minute };
}

/**
 * Returns current Argentina date in YYYY-MM-DD format (useful for `min` attributes)
 */
export function getArgentinaTodayISO(): string {
  const parts = getArgentinaDateTimeParts();
  const pad = (n: number) => n.toString().padStart(2, '0');
  return `${parts.year}-${pad(parts.month)}-${pad(parts.day)}`;
}

/**
 * Validates basic date time constraints strictly.
 */
export function isValidDateTime(date: string, time: string): boolean {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return false;
  if (!/^\d{2}:\d{2}$/.test(time)) return false;

  const [y, m, d] = date.split('-').map(Number);
  const [H, M] = time.split(':').map(Number);

  if (m < 1 || m > 12) return false;
  const daysInMonth = new Date(y, m, 0).getDate();
  if (d < 1 || d > daysInMonth) return false;

  if (H < 0 || H > 23) return false;
  if (M < 0 || M > 59) return false;

  return true;
}

/**
 * Builds canonical key like "YYYY-MM-DDTHH:MM"
 */
export function buildArgentinaLocalKey(date: string, time: string): string {
  return `${date}T${time}`;
}

/**
 * Returns 1 if a > b, -1 if a < b, 0 if equal.
 * Expects keys generated by buildArgentinaLocalKey.
 */
export function compareArgentinaLocalDateTimes(keyA: string, keyB: string): number {
  if (keyA > keyB) return 1;
  if (keyA < keyB) return -1;
  return 0;
}

/**
 * Checks if a given Argentina date/time is strictly in the future compared to now.
 */
export function isArgentinaDateTimeInFuture(date: string, time: string): boolean {
  if (!isValidDateTime(date, time)) return false;

  const targetKey = buildArgentinaLocalKey(date, time);
  const currentParts = getArgentinaDateTimeParts();

  const pad = (n: number) => n.toString().padStart(2, '0');
  const currentKey = `${currentParts.year}-${pad(currentParts.month)}-${pad(currentParts.day)}T${pad(currentParts.hour)}:${pad(currentParts.minute)}`;

  return targetKey > currentKey;
}

/**
 * Builds deadline ISO string with fixed Argentina offset.
 * Example: 2026-07-20T20:00:00-03:00
 */
export function buildArgentinaDeadlineIso(date: string, time: string): string | null {
  if (!isValidDateTime(date, time)) return null;
  return `${date}T${time}:00-03:00`;
}
